/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  // browserHistory,
  hashHistory,
} from 'react-router';

// 路由配置规则参考： https://github.com/ReactTraining/react-router/blob/v3/docs/guides/RouteConfiguration.md#configuration-with-plain-routes
// 一下部分是由 ICE 相关工具自动生成的路由，请勿随意改变，否则可能会出现一些异常情况
// <!-- auto generated routes start -->
import Group from './pages/Group';
import Collector from './pages/Collector';
import ActiveCollector from './pages/ActiveCollector';
import PassiveCollector from './pages/PassiveCollector';
import AgentCollector from './pages/AgentCollector';
import Parser from './pages/Parser';
import User from './pages/User';
import Cert from './pages/Cert';
import First from './pages/First';
import HeaderAsideFooterResponsiveLayout from './layouts/HeaderAsideFooterResponsiveLayout';
import BlankLayout from './layouts/BlankLayout';
import Login from './pages/Login';
import NotFound from './pages/NotFound';

const autoGeneratedRoutes = [
  {
    path: '/collector',
    childRoutes: [{
      path: 'active',
      childRoutes: [],
      component: ActiveCollector,
    }, {
      path: 'passive',
      childRoutes: [],
      component: PassiveCollector,
    }, {
      path: 'agent',
      childRoutes: [],
      component: AgentCollector,
    }],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: Collector,
    },
  },
  //   {
  //   path: '/collector',
  //   childRoutes: [

  //   ],
  //   component: HeaderAsideFooterResponsiveLayout,
  //   indexRoute: {
  //     component: Collector,
  //   },
  // }, 
  {
    path: '/parser',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: Parser,
    },
  }, {
    path: '/user',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: User,
    },
  }, {
    path: '/group',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: Group,
    },
  }, {
    path: '/cert',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: Cert,
    },
  }, {
    path: '/home',
    childRoutes: [],
    component: HeaderAsideFooterResponsiveLayout,
    indexRoute: {
      component: First,
    },
  }, {
    path: '/',
    childRoutes: [],
    component: BlankLayout,
    indexRoute: {
      component: Login // }, {
      //   path: '/setting',
      //   childRoutes: [{
      //     path: 'basic',
      //     childRoutes: [],
      //     component: BasicSetting
      //   }, {
      //     path: 'navigation',
      //     childRoutes: [],
      //     component: NavigationSetting
      //   }],
      //   component: HeaderAsideFooterResponsiveLayout,
      //   indexRoute: {
      //     component: BasicSetting
      //   }
      // }, {
      //   path: '/user',
      //   childRoutes: [{
      //     path: 'list',
      //     childRoutes: [],
      //     component: UserList
      //   }, {
      //     path: 'create',
      //     childRoutes: [],
      //     component: CreateUser
      //   }, {
      //     path: 'pwd',
      //     childRoutes: [],
      //     component: EditPassword
      //   }],
      //   component: HeaderAsideFooterResponsiveLayout,
      //   indexRoute: {
      //     component: UserList
      //   }
      // }, {
      //   path: '/tag',
      //   childRoutes: [{
      //     path: 'list',
      //     childRoutes: [],
      //     component: TagList
      //   }, {
      //     path: 'create',
      //     childRoutes: [],
      //     component: CreateTag
      //   }],
      //   component: HeaderAsideFooterResponsiveLayout,
      //   indexRoute: {
      //     component: TagList
      //   }
      // }, {
      //   path: '/cate',
      //   childRoutes: [{
      //     path: 'list',
      //     childRoutes: [],
      //     component: CateList
      //   }, {
      //     path: 'create',
      //     childRoutes: [],
      //     component: CreateCate
      //   }],
      //   component: HeaderAsideFooterResponsiveLayout,
      //   indexRoute: {
      //     component: CateList
      //   }
      // }, {
      //   path: '/post',
      //   childRoutes: [{
      //     path: 'list',
      //     childRoutes: [],
      //     component: PostList
      //   }, {
      //     path: 'create',
      //     childRoutes: [],
      //     component: CreatePost
      //   }],
      //   component: HeaderAsideFooterResponsiveLayout,
      //   indexRoute: {
      //     component: PostList
      //   }

    },
  }];
// <!-- auto generated routes end -->

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Router
    history={hashHistory}
    routes={[...autoGeneratedRoutes, ...customRoutes]}
  />
);
